---
target_group: kiosks

kiosk_user: kiosk
kiosk_group: kiosk
kiosk_home: "/home/{{ kiosk_user }}"
kiosk_shell: /bin/bash
kiosk_password_hash: "$6$replace-me-with-a-real-hash"

kiosk_enable_autologin: true
kiosk_install_desktop: true

rxterminal_package_name: rxterminal
rxterminal_install_script_url: https://packages.strixon.co.uk/install-rxterminal.sh

kiosk_base_packages:
  - curl
  - gdm3
  - gnome-shell
  - dbus-x11
  - xdg-utils
  - policykit-1

kiosk_desktop_packages:
  - ubuntu-desktop-minimal

kiosk_vm_guest_packages: []

update_os_packages: false
reboot_if_required: true
